import PDFDocument from "pdfkit";

// Builds an invoice PDF and returns it as a Buffer.
export const buildInvoicePDF = (invoice) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const brand = "#4338ca";
      const gray = "#6b708c";

      // Header
      doc
        .fillColor(brand)
        .fontSize(22)
        .font("Helvetica-Bold")
        .text("CRM Pro", 50, 50);

      doc
        .fillColor("#14162b")
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("INVOICE", 400, 50, { align: "right" });

      doc
        .fillColor(gray)
        .fontSize(10)
        .font("Helvetica")
        .text(invoice.invoiceNumber, 400, 75, { align: "right" });

      doc.moveDown(2);
      doc.moveTo(50, 100).lineTo(545, 100).strokeColor("#e6e8f0").stroke();

      // Bill To / Dates
      let y = 120;
      doc.fillColor(gray).fontSize(10).font("Helvetica-Bold").text("BILL TO", 50, y);
      doc.fillColor("#14162b").fontSize(12).font("Helvetica-Bold").text(invoice.contact?.name || "N/A", 50, y + 16);
      doc.fillColor(gray).fontSize(10).font("Helvetica").text(invoice.contact?.company || "", 50, y + 34);
      doc.text(invoice.contact?.email || "", 50, y + 48);

      doc.fillColor(gray).fontSize(10).font("Helvetica-Bold").text("ISSUE DATE", 350, y, { width: 100, align: "right" });
      doc.fillColor("#14162b").fontSize(11).font("Helvetica").text(
        invoice.issueDate ? new Date(invoice.issueDate).toLocaleDateString() : "-",
        350, y + 14, { width: 195, align: "right" }
      );
      doc.fillColor(gray).fontSize(10).font("Helvetica-Bold").text("DUE DATE", 350, y + 34, { width: 100, align: "right" });
      doc.fillColor("#14162b").fontSize(11).font("Helvetica").text(
        invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : "-",
        350, y + 48, { width: 195, align: "right" }
      );

      // Status badge
      doc.fillColor(brand).fontSize(10).font("Helvetica-Bold").text(`STATUS: ${invoice.status.toUpperCase()}`, 350, y + 68, { width: 195, align: "right" });

      // Table header
      y = 220;
      doc.rect(50, y, 495, 24).fill("#f6f7fb");
      doc.fillColor(gray).fontSize(10).font("Helvetica-Bold");
      doc.text("DESCRIPTION", 60, y + 7);
      doc.text("QTY", 340, y + 7, { width: 50, align: "right" });
      doc.text("PRICE", 400, y + 7, { width: 70, align: "right" });
      doc.text("AMOUNT", 475, y + 7, { width: 60, align: "right" });

      y += 24;
      doc.font("Helvetica").fillColor("#14162b").fontSize(10);

      (invoice.items || []).forEach((item) => {
        const amount = (item.quantity || 0) * (item.price || 0);
        doc.text(item.description, 60, y + 8, { width: 270 });
        doc.text(String(item.quantity), 340, y + 8, { width: 50, align: "right" });
        doc.text(`$${item.price.toLocaleString()}`, 400, y + 8, { width: 70, align: "right" });
        doc.text(`$${amount.toLocaleString()}`, 475, y + 8, { width: 60, align: "right" });
        doc.moveTo(50, y + 26).lineTo(545, y + 26).strokeColor("#e6e8f0").stroke();
        y += 26;
      });

      // Totals
      y += 14;
      const subtotal = invoice.subtotal ?? (invoice.items || []).reduce((s, i) => s + i.quantity * i.price, 0);
      const taxAmount = invoice.taxAmount ?? (subtotal * (invoice.taxRate || 0)) / 100;
      const total = invoice.total ?? Math.max(0, subtotal + taxAmount - (invoice.discount || 0));

      const totalsRow = (label, value, bold = false) => {
        doc.font(bold ? "Helvetica-Bold" : "Helvetica").fillColor(bold ? "#14162b" : gray).fontSize(bold ? 12 : 10);
        const formatted = value < 0 ? `-$${Math.abs(value).toLocaleString()}` : `$${value.toLocaleString()}`;
        doc.text(label, 350, y, { width: 100, align: "right" });
        doc.text(formatted, 460, y, { width: 85, align: "right" });
        y += bold ? 22 : 18;
      };

      totalsRow("Subtotal", subtotal);
      totalsRow(`Tax (${invoice.taxRate || 0}%)`, taxAmount);
      totalsRow("Discount", -(invoice.discount || 0));
      doc.moveTo(350, y).lineTo(545, y).strokeColor("#e6e8f0").stroke();
      y += 8;
      totalsRow("TOTAL", total, true);

      // Notes
      if (invoice.notes) {
        y += 30;
        doc.fillColor(gray).fontSize(10).font("Helvetica-Bold").text("NOTES", 50, y);
        doc.fillColor("#14162b").fontSize(10).font("Helvetica").text(invoice.notes, 50, y + 14, { width: 495 });
      }

      // Footer
      doc.fillColor(gray).fontSize(9).font("Helvetica").text(
        "Generated by CRM Pro — Thank you for your business!",
        50, 760, { width: 495, align: "center" }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
